[package]
name = "pain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.8"
tokio = { version = "1", features = ["full"] }
image = "0.25.5"
rayon = "1.8"
indicatif = "0.17"
num_cpus = "1.16"
